/*
SNOWFLAKE ML HCLS DEMO CLEANUP SCRIPT
Cleans up all objects created during the demo.
Requires ACCOUNTADMIN role.
*/

USE ROLE ACCOUNTADMIN;

-- drop compute pools 
DROP COMPUTE POOL IF EXISTS ML_DISTRIBUTED_GPU_POOL;
DROP COMPUTE POOL IF EXISTS ML_DISTRIBUTED_CPU_POOL;

-- drop warehouse
DROP WAREHOUSE IF EXISTS ADVERSE_EVENT_WH;

-- Drop database with all schemas and tables
DROP DATABASE IF EXISTS ADVERSE_EVENT_MONITORING CASCADE;